/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Controladores.ControladorGeneral;
import Controladores.EmpleadoControlador;
import Modelos.CacheEmpleado;
import Modelos.EmpleadosModelo;

/**
 *
 * @author fgodo
 */
public class EmpleadosPantalla extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public EmpleadosPantalla() {
        initComponents();
        EmpleadoControlador.Llenartablaempleado(tabla_empleados, "Todos"); 
        ControladorGeneral.Filtrotabla(tabla_empleados, txtbuscar_empleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btnagregar_empleado = new javax.swing.JButton();
        txtbuscar_empleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_empleados = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnagregar_empleado.setText("Agregar");
        btnagregar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_empleadoActionPerformed(evt);
            }
        });

        txtbuscar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar_empleadoActionPerformed(evt);
            }
        });

        tabla_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Identidad", "Nombre", "Telefono", "Fecha Nacimiento", "Direccion", "Fecha Ingreso", "Fecha Salida", "Correo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_empleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_empleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbuscar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnagregar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar_empleado)
                    .addComponent(txtbuscar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_empleadoActionPerformed
        EmpleadoControlador empco = new EmpleadoControlador();
        empco.setOperacion(0);
        Mantenimiento_empeadospantalla mantenimientoempleado = new Mantenimiento_empeadospantalla();
        mantenimientoempleado.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnagregar_empleadoActionPerformed

    private void tabla_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_empleadosMouseClicked
        int seleccion = this.tabla_empleados.rowAtPoint(evt.getPoint()); 
        EmpleadosModelo empleadomodelo = new EmpleadosModelo();
        EmpleadoControlador empco = new EmpleadoControlador();
        empleadomodelo.setEmpcodigo(Integer.parseInt(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion, 0)))); 
        empleadomodelo.setEmpidentidad(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion, 1)));
        empleadomodelo.setEmpnombre(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion, 2)));
        empleadomodelo.setEmptelefono(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion, 3)));
        empleadomodelo.setEmpfechanacimiento(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion, 4)));
        empleadomodelo.setEmpdireccion(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion, 5)));
        empleadomodelo.setEmpfechaingreso(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion,6))); 
        empleadomodelo.setEmpfechasalidad(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion,7))); 
        empleadomodelo.setEmpcorreo(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion,8))); 
        empleadomodelo.setEmpestado(String.valueOf(this.tabla_empleados.getModel().getValueAt(seleccion,9)));
        CacheEmpleado empleadocache = new CacheEmpleado();     
        empleadocache.Setdatoscompartidos(true);
        empleadocache.setEmpleado(empleadomodelo);
        empco.setOperacion(1);
        dispose();
        Mantenimiento_empeadospantalla mantenimientoempleado = new Mantenimiento_empeadospantalla();
        
        mantenimientoempleado.setVisible(true);
    }//GEN-LAST:event_tabla_empleadosMouseClicked

    private void txtbuscar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscar_empleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar_empleado;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_empleados;
    private javax.swing.JTextField txtbuscar_empleado;
    // End of variables declaration//GEN-END:variables
}
