/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Controladores.EmpleadoControlador;
import Especiales.PlaceHolder;
import Especiales.Validaciones;
import Modelos.EmpleadosModelo;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fgodo
 */
public class Mantenimiento_empeadospantalla extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento_empeadospantalla
     */
    PlaceHolder fecha;
    static Integer IdEmp=0;
    Integer mt;
    
    static String puesto_nombre ="";
    
    public Mantenimiento_empeadospantalla() {
        initComponents();
        EmpleadoControlador empleadocontrol = new EmpleadoControlador();
        //fecha = new PlaceHolder(jdfechanacimiento_empleado,"Fecha de Nacimiento");
        EmpleadoControlador.setPlaceHolders(this.txtidentidad_empleado, this.txtnombre_empleado, this.txttelefono_empleado,
                this.txtcorre_empleado,this.txtdireccion_empleado,this.txtusuario_empleado,
                this.txtcontrasena_empleado,this.txtcontrasenac_empleado);
        mt = empleadocontrol.getOperacion();
        if(mt == 1){ LlenarDatos(); }
        EmpleadoControlador.Llenarcmbpuestos(this.cmbpuestos_empelados);
    }
        private void Proceso(Integer op)
    {
        mt = op;       
    }
    
    private void LlenarDatos()
    {
        this.IdEmp = EmpleadoControlador.SetdatosromCache(this.txtidentidad_empleado,
                this.txtnombre_empleado, this.txttelefono_empleado, this.jdfechanacimiento_empleado,
                this.txtdireccion_empleado ,this.jdfechaingreso_empleado ,this.jdfechasalida_empleado,
                this.txtcorre_empleado,this.cmbestado_empleado,this.txtusuario_empleado);
                 EmpleadoControlador.Llenartablaempleadopuestos(tabla_puesto,IdEmp);
                
        if(IdEmp != null)
        {
            this.btnagregar_empleado.setEnabled(false);
            this.txtcontrasena_empleado.setEnabled(false);
            this.txtcontrasenac_empleado.setEnabled(false);
            this.btnagregar_empleado.setEnabled(false);
            this.btnmodificar_empleado.setEnabled(true);
            this.btn_eliminar_empleado.setEnabled(true);
            
        }
    }    

    private void LimpiarTodo(){
        DefaultTableModel model =(DefaultTableModel) tabla_puesto.getModel();
        int fila= model.getRowCount();
        for(int i = 0; i < fila; i++  )
        {       
                model.removeRow(0);  
        }
    }      
    
    private void LimpiarInputs()
    {
        this.txtidentidad_empleado.setText(null);
        this.txtnombre_empleado.setText(null);
        this.txttelefono_empleado.setText(null);
        this.txtcorre_empleado.setText(null);
        this.txtdireccion_empleado.setText(null);
        this.txttelefono_empleado.setText(null);     
        this.jdfechanacimiento_empleado.setCalendar(null);
        this.jdfechaingreso_empleado.setCalendar(null);
        this.jdfechasalida_empleado.setCalendar(null);       
    }    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        btnagregar_empleado = new javax.swing.JButton();
        btnmodificar_empleado = new javax.swing.JButton();
        btn_eliminar_empleado = new javax.swing.JButton();
        erridentidad = new javax.swing.JLabel();
        errnombre = new javax.swing.JLabel();
        errtelefono = new javax.swing.JLabel();
        errfechana = new javax.swing.JLabel();
        txtidentidad_empleado = new javax.swing.JTextField();
        errcorreo = new javax.swing.JLabel();
        txtnombre_empleado = new javax.swing.JTextField();
        errdireccion = new javax.swing.JLabel();
        txtcontrasenac_empleado = new javax.swing.JPasswordField();
        txttelefono_empleado = new javax.swing.JTextField();
        jdfechanacimiento_empleado = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdireccion_empleado = new javax.swing.JTextArea();
        jdfechaingreso_empleado = new com.toedter.calendar.JDateChooser();
        jdfechasalida_empleado = new com.toedter.calendar.JDateChooser();
        txtcorre_empleado = new javax.swing.JTextField();
        errfechain = new javax.swing.JLabel();
        errfechasa = new javax.swing.JLabel();
        cmbestado_empleado = new javax.swing.JComboBox<>();
        txtusuario_empleado = new javax.swing.JTextField();
        errcontrasena = new javax.swing.JLabel();
        errusuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcontrasena_empleado = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        cmbpuestos_empelados = new javax.swing.JComboBox<>();
        btnagregarpuesto_empleado = new javax.swing.JButton();
        btneliminarpuesto_empleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_puesto = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton6.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(43, 47, 61));

        btnagregar_empleado.setBackground(new java.awt.Color(70, 104, 116));
        btnagregar_empleado.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar_empleado.setText("Agregar");
        btnagregar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_empleadoActionPerformed(evt);
            }
        });

        btnmodificar_empleado.setBackground(new java.awt.Color(70, 104, 116));
        btnmodificar_empleado.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar_empleado.setText("Modificar");
        btnmodificar_empleado.setEnabled(false);
        btnmodificar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_empleadoActionPerformed(evt);
            }
        });

        btn_eliminar_empleado.setBackground(new java.awt.Color(70, 104, 116));
        btn_eliminar_empleado.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar_empleado.setText("Eliminar");
        btn_eliminar_empleado.setEnabled(false);
        btn_eliminar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_empleadoActionPerformed(evt);
            }
        });

        erridentidad.setForeground(new java.awt.Color(255, 51, 51));

        errnombre.setForeground(new java.awt.Color(255, 51, 51));

        errtelefono.setForeground(new java.awt.Color(255, 51, 51));

        errfechana.setForeground(new java.awt.Color(255, 51, 51));

        errcorreo.setForeground(new java.awt.Color(255, 51, 51));

        txtnombre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_empleadoActionPerformed(evt);
            }
        });

        errdireccion.setForeground(new java.awt.Color(255, 51, 51));

        txttelefono_empleado.setToolTipText("");
        txttelefono_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefono_empleadoActionPerformed(evt);
            }
        });

        jdfechanacimiento_empleado.setToolTipText("");
        jdfechanacimiento_empleado.setDateFormatString("yyyy-MM-dd");
        jdfechanacimiento_empleado.setFocusCycleRoot(true);

        txtdireccion_empleado.setColumns(20);
        txtdireccion_empleado.setRows(5);
        jScrollPane1.setViewportView(txtdireccion_empleado);

        jdfechaingreso_empleado.setToolTipText("2021-10-10");
        jdfechaingreso_empleado.setDateFormatString("yyyy-MM-dd");

        jdfechasalida_empleado.setDateFormatString("yyyy-MM-dd");
        jdfechasalida_empleado.setEnabled(false);

        txtcorre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorre_empleadoActionPerformed(evt);
            }
        });

        errfechain.setForeground(new java.awt.Color(255, 51, 51));

        errfechasa.setForeground(new java.awt.Color(255, 51, 51));

        cmbestado_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACT", "INA" }));
        cmbestado_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestado_empleadoActionPerformed(evt);
            }
        });

        errcontrasena.setForeground(new java.awt.Color(255, 51, 51));

        errusuario.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha Ingreso:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Salida:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Nacimiento:");

        jPanel1.setBackground(new java.awt.Color(43, 47, 61));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnagregarpuesto_empleado.setBackground(new java.awt.Color(70, 104, 116));
        btnagregarpuesto_empleado.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarpuesto_empleado.setText("Agregar");
        btnagregarpuesto_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarpuesto_empleadoActionPerformed(evt);
            }
        });

        btneliminarpuesto_empleado.setBackground(new java.awt.Color(70, 104, 116));
        btneliminarpuesto_empleado.setForeground(new java.awt.Color(255, 255, 255));
        btneliminarpuesto_empleado.setText("Eliminar");
        btneliminarpuesto_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarpuesto_empleadoActionPerformed(evt);
            }
        });

        tabla_puesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Puestos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_puestoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_puesto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbpuestos_empelados, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregarpuesto_empleado)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminarpuesto_empleado)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbpuestos_empelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarpuesto_empleado)
                    .addComponent(btneliminarpuesto_empleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 230, 230));
        jLabel5.setText("Mantenimiento de Empleados");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fgodo\\OneDrive\\Documentos\\GitHub\\proyectotiendarepuestos\\pry_TiendaRepuestos\\src\\Imagenes\\Logomantenimiento.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errcorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttelefono_empleado)
                                    .addComponent(txtidentidad_empleado)
                                    .addComponent(txtnombre_empleado)
                                    .addComponent(erridentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errtelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcorre_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcontrasenac_empleado)
                                    .addComponent(errcontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtusuario_empleado)
                                    .addComponent(errusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbestado_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcontrasena_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errfechana, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jdfechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(errfechain, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jdfechaingreso_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errfechasa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jdfechasalida_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnagregar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmodificar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtidentidad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtusuario_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(erridentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcontrasena_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(errusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0)
                                .addComponent(errnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 114, Short.MAX_VALUE)
                                .addComponent(errcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcontrasenac_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcorre_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbestado_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(errcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jdfechasalida_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(errfechasa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jdfechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(errfechana, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdfechaingreso_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errfechain, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmodificar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnagregar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefono_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono_empleadoActionPerformed

    private void txtcorre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorre_empleadoActionPerformed

    private void btnagregar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_empleadoActionPerformed

    
    if(!EmpleadoControlador.Mantenimientoempelado("insertar", 0,
            this.txtidentidad_empleado.getText(),this.txtnombre_empleado.getText(), this.txttelefono_empleado.getText(), Validaciones.Fechavacia(jdfechanacimiento_empleado.getDate()),
            this.txtcorre_empleado.getText(), this.txtdireccion_empleado.getText(),Validaciones.Fechavacia(jdfechaingreso_empleado.getDate()),"0000-00-00","ACT",
            this.txtusuario_empleado.getText(),this.txtcontrasena_empleado.getText(),this.txtcontrasenac_empleado.getText(),this.erridentidad, 
            this.errnombre, this.errtelefono, this.errfechana, this.errcorreo,this.errdireccion, this.errfechain,this.errfechain,this.errusuario,this.errcontrasena))
        {           
            this.LimpiarInputs();
            LimpiarTodo();
            EmpleadosPantalla empleadopantalla = new EmpleadosPantalla();
            empleadopantalla.setVisible(true); 
            dispose();
        }   
    }//GEN-LAST:event_btnagregar_empleadoActionPerformed

    private void btnagregarpuesto_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarpuesto_empleadoActionPerformed
          EmpleadoControlador.AgregarPuesto(new Object[]{cmbpuestos_empelados.getSelectedItem().toString()}, tabla_puesto);
    }//GEN-LAST:event_btnagregarpuesto_empleadoActionPerformed

    private void btneliminarpuesto_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarpuesto_empleadoActionPerformed
        EmpleadoControlador.Quitarpuestosseleccionados(puesto_nombre,tabla_puesto );
    }//GEN-LAST:event_btneliminarpuesto_empleadoActionPerformed

    private void tabla_puestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_puestoMouseClicked
        int seleccion = this.tabla_puesto.rowAtPoint(evt.getPoint());    
        puesto_nombre =String.valueOf(this.tabla_puesto.getModel().getValueAt(seleccion, 0));    
    }//GEN-LAST:event_tabla_puestoMouseClicked

    private void btnmodificar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_empleadoActionPerformed
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
    String Date;
        if(!EmpleadoControlador.Mantenimientoempelado("editar", this.IdEmp,
            this.txtidentidad_empleado.getText(),this.txtnombre_empleado.getText(), this.txttelefono_empleado.getText(),Validaciones.Fechavacia(jdfechanacimiento_empleado.getDate()),
            this.txtcorre_empleado.getText(), this.txtdireccion_empleado.getText(),Validaciones.Fechavacia(jdfechaingreso_empleado.getDate()),"0000-00-00",cmbestado_empleado.getSelectedItem().toString(),
            this.txtusuario_empleado.getText(),"Nopermitid@12","Nopermitid@12",
            this.erridentidad, this.errnombre, this.errtelefono, this.errfechana, this.errcorreo,
            this.errdireccion, this.errfechain,this.errfechain,this.errusuario,this.errcontrasena))
        {
            this.LimpiarInputs();
            LimpiarTodo();
            EmpleadosPantalla empleadopantalla = new EmpleadosPantalla();
            empleadopantalla.setVisible(true); 
            dispose();
            
        }            
    }//GEN-LAST:event_btnmodificar_empleadoActionPerformed

    private void btn_eliminar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_empleadoActionPerformed

        if(EmpleadoControlador.Eliminarempleo(this.IdEmp))
        {
            this.LimpiarInputs();
            LimpiarTodo();
            EmpleadosPantalla empleadopantalla = new EmpleadosPantalla();
            empleadopantalla.setVisible(true); 
            dispose();
            
        }         
    }//GEN-LAST:event_btn_eliminar_empleadoActionPerformed

    private void cmbestado_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestado_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestado_empleadoActionPerformed

    private void txtnombre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_empleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento_empeadospantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar_empleado;
    private javax.swing.JButton btnagregar_empleado;
    private javax.swing.JButton btnagregarpuesto_empleado;
    private javax.swing.JButton btneliminarpuesto_empleado;
    private javax.swing.JButton btnmodificar_empleado;
    private javax.swing.JComboBox<String> cmbestado_empleado;
    private javax.swing.JComboBox<String> cmbpuestos_empelados;
    private javax.swing.JLabel errcontrasena;
    private javax.swing.JLabel errcorreo;
    private javax.swing.JLabel errdireccion;
    private javax.swing.JLabel errfechain;
    private javax.swing.JLabel errfechana;
    private javax.swing.JLabel errfechasa;
    private javax.swing.JLabel erridentidad;
    private javax.swing.JLabel errnombre;
    private javax.swing.JLabel errtelefono;
    private javax.swing.JLabel errusuario;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdfechaingreso_empleado;
    private com.toedter.calendar.JDateChooser jdfechanacimiento_empleado;
    private com.toedter.calendar.JDateChooser jdfechasalida_empleado;
    public static javax.swing.JTable tabla_puesto;
    private javax.swing.JPasswordField txtcontrasena_empleado;
    private javax.swing.JPasswordField txtcontrasenac_empleado;
    private javax.swing.JTextField txtcorre_empleado;
    private javax.swing.JTextArea txtdireccion_empleado;
    private javax.swing.JTextField txtidentidad_empleado;
    private javax.swing.JTextField txtnombre_empleado;
    private javax.swing.JTextField txttelefono_empleado;
    private javax.swing.JTextField txtusuario_empleado;
    // End of variables declaration//GEN-END:variables
}
