/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Controladores.ProveedorControlador;
import javax.swing.UIManager;

/**
 *
 * @author fgodo
 */
public class Mantenimiento_proveedorPantalla extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento_proveedorPantalla
     */
    static Integer IdPro=0;
    Integer mt;
    public Mantenimiento_proveedorPantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
        ProveedorControlador proveedorcontrol = new ProveedorControlador(); 
        
        ProveedorControlador.setPlaceHolders(this.txtnombre_proveedor, this.txttelefono_proveedor,this.txtdireccion_proveedor);        
        
        mt = proveedorcontrol.getOperacion();
        if(mt == 1){ LlenarDatos(); }
    }

    private void LlenarDatos()
    {
        this.IdPro = ProveedorControlador.SetdatosromCache(this.txtnombre_proveedor, 
                this.txttelefono_proveedor, this.txtdireccion_proveedor ,this.cmbestado_proveedor);
                
        if(IdPro != null)
        {
            this.btnagregar_proveedor.setEnabled(false);
            this.btnmodificar_proveedor.setEnabled(true);
            this.btn_eliminar_proveedor.setEnabled(true);
            cmbestado_proveedor.setEnabled(true);
        }
    }      
    
    
    private void LimpiarInputs()
    {
        this.txtnombre_proveedor.setText(null);
        this.txttelefono_proveedor.setText(null);
        this.txtdireccion_proveedor.setText(null);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnagregar_proveedor = new javax.swing.JButton();
        btnmodificar_proveedor = new javax.swing.JButton();
        btn_eliminar_proveedor = new javax.swing.JButton();
        errnombre = new javax.swing.JLabel();
        errtelefono = new javax.swing.JLabel();
        txtnombre_proveedor = new javax.swing.JTextField();
        errdireccion = new javax.swing.JLabel();
        txttelefono_proveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdireccion_proveedor = new javax.swing.JTextArea();
        cmbestado_proveedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(43, 47, 61));

        btnagregar_proveedor.setBackground(new java.awt.Color(70, 104, 116));
        btnagregar_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar_proveedor.setText("Agregar");
        btnagregar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_proveedorActionPerformed(evt);
            }
        });

        btnmodificar_proveedor.setBackground(new java.awt.Color(70, 104, 116));
        btnmodificar_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar_proveedor.setText("Modificar");
        btnmodificar_proveedor.setEnabled(false);
        btnmodificar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_proveedorActionPerformed(evt);
            }
        });

        btn_eliminar_proveedor.setBackground(new java.awt.Color(70, 104, 116));
        btn_eliminar_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar_proveedor.setText("Eliminar");
        btn_eliminar_proveedor.setEnabled(false);
        btn_eliminar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_proveedorActionPerformed(evt);
            }
        });

        errnombre.setForeground(new java.awt.Color(255, 51, 51));

        errtelefono.setForeground(new java.awt.Color(255, 51, 51));

        txtnombre_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_proveedorActionPerformed(evt);
            }
        });

        errdireccion.setForeground(new java.awt.Color(255, 51, 51));

        txttelefono_proveedor.setToolTipText("");
        txttelefono_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefono_proveedorActionPerformed(evt);
            }
        });

        txtdireccion_proveedor.setColumns(20);
        txtdireccion_proveedor.setRows(5);
        jScrollPane1.setViewportView(txtdireccion_proveedor);

        cmbestado_proveedor.setBackground(new java.awt.Color(70, 104, 116));
        cmbestado_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        cmbestado_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACT", "INA" }));
        cmbestado_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbestado_proveedorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mantenimiento de Proveedor");

        jButton1.setBackground(new java.awt.Color(70, 104, 116));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logomantenimiento.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnagregar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmodificar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(errnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtnombre_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txttelefono_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmbestado_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(errtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(errdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(93, 93, 93))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttelefono_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbestado_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregar_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbestado_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestado_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestado_proveedorActionPerformed

    private void txttelefono_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono_proveedorActionPerformed

    private void txtnombre_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_proveedorActionPerformed

    private void btn_eliminar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_proveedorActionPerformed

        if(ProveedorControlador.Eliminarproveedor(this.IdPro))
        {
            this.LimpiarInputs();
            ProveedoresPantalla pantalla = new ProveedoresPantalla();
            pantalla.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_btn_eliminar_proveedorActionPerformed

    private void btnmodificar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_proveedorActionPerformed

    if(!ProveedorControlador.Mantenimientoproveedor("editar", this.IdPro,
            this.txtnombre_proveedor.getText(), this.txttelefono_proveedor.getText(), this.txtdireccion_proveedor.getText(),
            cmbestado_proveedor.getSelectedItem().toString(), this.errnombre, this.errtelefono,
            this.errdireccion))
    {
        this.LimpiarInputs();
        ProveedoresPantalla pantalla = new ProveedoresPantalla();
        pantalla.setVisible(true);
        dispose();       
    }    
    }//GEN-LAST:event_btnmodificar_proveedorActionPerformed

    private void btnagregar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_proveedorActionPerformed

    if(!ProveedorControlador.Mantenimientoproveedor("insertar", 0,
            this.txtnombre_proveedor.getText(), this.txttelefono_proveedor.getText(), this.txtdireccion_proveedor.getText(),
            cmbestado_proveedor.getSelectedItem().toString(), this.errnombre, this.errtelefono,
            this.errdireccion))
    {
        this.LimpiarInputs();
        ProveedoresPantalla pantalla = new ProveedoresPantalla();
        pantalla.setVisible(true);
        dispose();       
    }    
    }//GEN-LAST:event_btnagregar_proveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrincipalPantalla menu = new MenuPrincipalPantalla();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           // UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
           UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento_proveedorPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar_proveedor;
    private javax.swing.JButton btnagregar_proveedor;
    private javax.swing.JButton btnmodificar_proveedor;
    private javax.swing.JComboBox<String> cmbestado_proveedor;
    private javax.swing.JLabel errdireccion;
    private javax.swing.JLabel errnombre;
    private javax.swing.JLabel errtelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtdireccion_proveedor;
    private javax.swing.JTextField txtnombre_proveedor;
    private javax.swing.JTextField txttelefono_proveedor;
    // End of variables declaration//GEN-END:variables
}
