/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Controladores.MarcaControlador;
import javax.swing.UIManager;

/**
 *
 * @author marce
 */
public class Mantenimiento_marcapantalla extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento_marcapantalla
     */
    static Integer IdMar=0;
    static String marca_nombre ="";
    Integer mt;
    public Mantenimiento_marcapantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
        MarcaControlador controlador = new MarcaControlador();
        MarcaControlador.setPlaceHolders(this.txtmarcas_descripcion);
        mt = controlador.getOperacion();
        if(mt == 1){ LlenarDatos(); }
    }

    private void LlenarDatos()
    {
        this.IdMar = MarcaControlador.SetdatosromCache(this.txtmarcas_descripcion,this.cmbmarca_estado);
                
        if(IdMar != null)
        {            
            this.btnagregar_marca.setEnabled(false);
            this.btnmodificar_marca.setEnabled(true);
            this.btneliminar_marca.setEnabled(true);
            this.cmbmarca_estado.setEnabled(true);
        }
    }
    private void LimpiarInputs()
    {
        this.txtmarcas_descripcion.setText(null);
  
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtmarcas_descripcion = new javax.swing.JTextField();
        btnagregar_marca = new javax.swing.JButton();
        btnmodificar_marca = new javax.swing.JButton();
        btneliminar_marca = new javax.swing.JButton();
        cmbmarca_estado = new javax.swing.JComboBox<>();
        lberrordescripcion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 47, 61));

        txtmarcas_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarcas_descripcionActionPerformed(evt);
            }
        });

        btnagregar_marca.setBackground(new java.awt.Color(70, 104, 116));
        btnagregar_marca.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar_marca.setText("Agregar");
        btnagregar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_marcaActionPerformed(evt);
            }
        });

        btnmodificar_marca.setBackground(new java.awt.Color(70, 104, 116));
        btnmodificar_marca.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar_marca.setText("Modificar");
        btnmodificar_marca.setEnabled(false);
        btnmodificar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_marcaActionPerformed(evt);
            }
        });

        btneliminar_marca.setBackground(new java.awt.Color(70, 104, 116));
        btneliminar_marca.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar_marca.setText("Eliminar");
        btneliminar_marca.setEnabled(false);
        btneliminar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_marcaActionPerformed(evt);
            }
        });

        cmbmarca_estado.setBackground(new java.awt.Color(70, 104, 116));
        cmbmarca_estado.setForeground(new java.awt.Color(255, 255, 255));
        cmbmarca_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACT", "INA" }));
        cmbmarca_estado.setEnabled(false);

        lberrordescripcion.setForeground(new java.awt.Color(255, 51, 51));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mantenimiento de Marcas");

        btnregresar.setBackground(new java.awt.Color(70, 104, 116));
        btnregresar.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logomantenimiento.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnagregar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnmodificar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btneliminar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lberrordescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtmarcas_descripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(cmbmarca_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(68, 68, 68))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarcas_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmarca_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lberrordescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmarcas_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarcas_descripcionActionPerformed

    }//GEN-LAST:event_txtmarcas_descripcionActionPerformed

    private void btnagregar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_marcaActionPerformed

        if(!MarcaControlador.Mantenimientomarcas("insertar", this.IdMar,
            this.txtmarcas_descripcion.getText(),"ACT",this.lberrordescripcion))
    {
        this.LimpiarInputs();
        MarcasPantalla pantalla = new MarcasPantalla();
        pantalla.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_btnagregar_marcaActionPerformed

    private void btnmodificar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_marcaActionPerformed
        if(!MarcaControlador.Mantenimientomarcas("editar", this.IdMar,
            this.txtmarcas_descripcion.getText(),this.cmbmarca_estado.getSelectedItem().toString(),lberrordescripcion))
    {
        this.LimpiarInputs();
        MarcasPantalla pantalla = new MarcasPantalla();
        pantalla.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_btnmodificar_marcaActionPerformed

    private void btneliminar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_marcaActionPerformed
        if(MarcaControlador.Eliminarmarca(this.IdMar))
        {
            this.LimpiarInputs();
            MarcasPantalla pantalla = new MarcasPantalla();
            pantalla.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btneliminar_marcaActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        MarcasPantalla pantalla = new MarcasPantalla();
        pantalla.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           // UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
           UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento_marcapantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar_marca;
    private javax.swing.JButton btneliminar_marca;
    private javax.swing.JButton btnmodificar_marca;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cmbmarca_estado;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lberrordescripcion;
    private javax.swing.JTextField txtmarcas_descripcion;
    // End of variables declaration//GEN-END:variables
}
