/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Controladores.EmpleadoControlador;
import Modelos.EmpleadosModelo;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fgodo
 */
public class Mantenimiento_empeadospantalla extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento_empeadospantalla
     */
   
    static Integer IdEmp=0;
    static String puesto_nombre ="";
    Integer mt;

    
    
    public Mantenimiento_empeadospantalla() {
        initComponents();
        EmpleadoControlador empleadocontrol = new EmpleadoControlador();
        mt = empleadocontrol.getOperacion();
        if(mt == 1){ LlenarDatos(); }
        EmpleadoControlador.Llenarcmbpuestos(this.cmbpuestos_empelados);
    }
        private void Proceso(Integer op)
    {
        mt = op;       
    }
    
    private void LlenarDatos()
    {
        this.IdEmp = EmpleadoControlador.SetdatosromCache(this.txtidentidad_empleado,
                this.txtnombre_empleado, this.txttelefono_empleado, this.jdfechanacimiento_empleado,
                this.txtdireccion_empleado ,this.jdfechaingreso_empleado ,this.jdfechasalida_empleado,
                this.txtcorre_empleado,this.cmbestado_empleado);
                
        if(IdEmp != null)
        {
            
            this.btnagregar_empleado.setEnabled(false);
            this.btnmodificar_empleado.setEnabled(true);
            this.btn_eliminar_empleado.setEnabled(true);
            jdfechasalida_empleado.setEnabled(true);
        }
    }    
    private void LimpiarTable(){
        DefaultTableModel model =(DefaultTableModel) tabla_puesto.getModel();
        int fila= model.getRowCount();
        for(int i = 0; i < fila; i++  )
        {       
                model.removeRow(0);  
        }
    }       
    private void LimpiarInputs()
    {
        this.txtidentidad_empleado.setText(null);
        this.txtnombre_empleado.setText(null);
        this.txttelefono_empleado.setText(null);
        this.txtcorre_empleado.setText(null);
        this.txtdireccion_empleado.setText(null);
        this.txttelefono_empleado.setText(null);     
        this.jdfechanacimiento_empleado.setCalendar(null);
        this.jdfechaingreso_empleado.setCalendar(null);
        this.jdfechasalida_empleado.setCalendar(null);       
    }    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        txtidentidad_empleado = new javax.swing.JTextField();
        txtnombre_empleado = new javax.swing.JTextField();
        txttelefono_empleado = new javax.swing.JTextField();
        jdfechanacimiento_empleado = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdireccion_empleado = new javax.swing.JTextArea();
        jdfechaingreso_empleado = new com.toedter.calendar.JDateChooser();
        jdfechasalida_empleado = new com.toedter.calendar.JDateChooser();
        txtcorre_empleado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cmbpuestos_empelados = new javax.swing.JComboBox<>();
        btnagregarpuesto_empleado = new javax.swing.JButton();
        btneliminarpuesto_empleado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_puesto = new javax.swing.JTable();
        btnagregar_empleado = new javax.swing.JButton();
        btnmodificar_empleado = new javax.swing.JButton();
        btn_eliminar_empleado = new javax.swing.JButton();
        erridentidad = new javax.swing.JLabel();
        errnombre = new javax.swing.JLabel();
        errtelefono = new javax.swing.JLabel();
        errfechana = new javax.swing.JLabel();
        errcorreo = new javax.swing.JLabel();
        errdireccion = new javax.swing.JLabel();
        errfechain = new javax.swing.JLabel();
        errfechasa = new javax.swing.JLabel();
        cmbestado_empleado = new javax.swing.JComboBox<>();

        jButton6.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txttelefono_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefono_empleadoActionPerformed(evt);
            }
        });

        jdfechanacimiento_empleado.setToolTipText("");
        jdfechanacimiento_empleado.setDateFormatString("yyyy-MM-dd");

        txtdireccion_empleado.setColumns(20);
        txtdireccion_empleado.setRows(5);
        jScrollPane1.setViewportView(txtdireccion_empleado);

        jdfechaingreso_empleado.setToolTipText("2021-10-10");
        jdfechaingreso_empleado.setDateFormatString("yyyy-MM-dd");

        jdfechasalida_empleado.setDateFormatString("yyyy-MM-dd");
        jdfechasalida_empleado.setEnabled(false);

        txtcorre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorre_empleadoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Puesto"));

        btnagregarpuesto_empleado.setText("Agregar");
        btnagregarpuesto_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarpuesto_empleadoActionPerformed(evt);
            }
        });

        btneliminarpuesto_empleado.setText("Eliminar");
        btneliminarpuesto_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarpuesto_empleadoActionPerformed(evt);
            }
        });

        tabla_puesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Puestos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_puestoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_puesto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbpuestos_empelados, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnagregarpuesto_empleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminarpuesto_empleado)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbpuestos_empelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarpuesto_empleado)
                    .addComponent(btneliminarpuesto_empleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnagregar_empleado.setText("Agregar");
        btnagregar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_empleadoActionPerformed(evt);
            }
        });

        btnmodificar_empleado.setText("Modificar");
        btnmodificar_empleado.setEnabled(false);
        btnmodificar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_empleadoActionPerformed(evt);
            }
        });

        btn_eliminar_empleado.setText("Eliminar");
        btn_eliminar_empleado.setEnabled(false);

        cmbestado_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACT", "INA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnagregar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmodificar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcorre_empleado)
                            .addComponent(txtidentidad_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttelefono_empleado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdfechanacimiento_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(erridentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errtelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errfechana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errcorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errfechasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jdfechaingreso_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdfechasalida_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errdireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errfechain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbestado_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbestado_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtidentidad_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(erridentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttelefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jdfechanacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errfechana, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcorre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(errcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jdfechaingreso_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errfechain, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdfechasalida_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(errfechasa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefono_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono_empleadoActionPerformed

    private void txtcorre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorre_empleadoActionPerformed

    private void btnagregar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_empleadoActionPerformed
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
    String Date;
        if(!EmpleadoControlador.Mantenimientoempelado("insertar", 0,
            this.txtidentidad_empleado.getText(),this.txtnombre_empleado.getText(), this.txttelefono_empleado.getText(), Date = formatter.format(jdfechanacimiento_empleado.getDate()),
            this.txtcorre_empleado.getText(), this.txtdireccion_empleado.getText(),Date = formatter.format(jdfechaingreso_empleado.getDate()),"0000-00-00","ACT",
            this.erridentidad, this.errnombre, this.errtelefono, this.errfechana, this.errcorreo,
            this.errdireccion, this.errfechain,this.errfechain ))
        {           
            this.LimpiarInputs();
            EmpleadosPantalla empleadopantalla = new EmpleadosPantalla();
            empleadopantalla.setVisible(true); 
            dispose();
        }    
    }//GEN-LAST:event_btnagregar_empleadoActionPerformed

    private void btnagregarpuesto_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarpuesto_empleadoActionPerformed
          EmpleadoControlador.AgregarPuesto(new Object[]{cmbpuestos_empelados.getSelectedItem().toString()}, tabla_puesto);
    }//GEN-LAST:event_btnagregarpuesto_empleadoActionPerformed

    private void btneliminarpuesto_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarpuesto_empleadoActionPerformed
        EmpleadoControlador.Quitarpuestosseleccionados(puesto_nombre,tabla_puesto );
    }//GEN-LAST:event_btneliminarpuesto_empleadoActionPerformed

    private void tabla_puestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_puestoMouseClicked
        int seleccion = this.tabla_puesto.rowAtPoint(evt.getPoint());    
        puesto_nombre =String.valueOf(this.tabla_puesto.getModel().getValueAt(seleccion, 0));    
    }//GEN-LAST:event_tabla_puestoMouseClicked

    private void btnmodificar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_empleadoActionPerformed
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
    String Date;
        if(!EmpleadoControlador.Mantenimientoempelado("editar", this.IdEmp,
            this.txtidentidad_empleado.getText(),this.txtnombre_empleado.getText(), this.txttelefono_empleado.getText(), Date = formatter.format(jdfechanacimiento_empleado.getDate()),
            this.txtcorre_empleado.getText(), this.txtdireccion_empleado.getText(),Date = formatter.format(jdfechaingreso_empleado.getDate()),"0000-00-00",cmbestado_empleado.getSelectedItem().toString(),
            this.erridentidad, this.errnombre, this.errtelefono, this.errfechana, this.errcorreo,
            this.errdireccion, this.errfechain,this.errfechain ))
        {
            this.LimpiarInputs();
            EmpleadosPantalla empleadopantalla = new EmpleadosPantalla();
            empleadopantalla.setVisible(true); 
            dispose();
            
        }            
    }//GEN-LAST:event_btnmodificar_empleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_empeadospantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento_empeadospantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar_empleado;
    private javax.swing.JButton btnagregar_empleado;
    private javax.swing.JButton btnagregarpuesto_empleado;
    private javax.swing.JButton btneliminarpuesto_empleado;
    private javax.swing.JButton btnmodificar_empleado;
    private javax.swing.JComboBox<String> cmbestado_empleado;
    private javax.swing.JComboBox<String> cmbpuestos_empelados;
    private javax.swing.JLabel errcorreo;
    private javax.swing.JLabel errdireccion;
    private javax.swing.JLabel errfechain;
    private javax.swing.JLabel errfechana;
    private javax.swing.JLabel errfechasa;
    private javax.swing.JLabel erridentidad;
    private javax.swing.JLabel errnombre;
    private javax.swing.JLabel errtelefono;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdfechaingreso_empleado;
    private com.toedter.calendar.JDateChooser jdfechanacimiento_empleado;
    private com.toedter.calendar.JDateChooser jdfechasalida_empleado;
    private javax.swing.JTable tabla_puesto;
    private javax.swing.JTextField txtcorre_empleado;
    private javax.swing.JTextArea txtdireccion_empleado;
    private javax.swing.JTextField txtidentidad_empleado;
    private javax.swing.JTextField txtnombre_empleado;
    private javax.swing.JTextField txttelefono_empleado;
    // End of variables declaration//GEN-END:variables
}
