/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Controladores.PuestoControlador;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author fgodo
 */
public class Mantenimiento_puestopantalla extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento_puestopantalla
     */
    static Integer IdPue=0;
    static String puesto_nombre ="";
    Integer mt;
    public Mantenimiento_puestopantalla() {
        initComponents();
        PuestoControlador puestocontrolador = new PuestoControlador();
        PuestoControlador.setPlaceHolders(this.txtpuesto_descripcion);
        mt = puestocontrolador.getOperacion();
        if(mt == 1){ LlenarDatos(); }
    }
    
    private void LlenarDatos()
    {
        this.IdPue = PuestoControlador.SetdatosromCache(this.txtpuesto_descripcion,this.cmbuesto_estado);
                
        if(IdPue != null)
        {            
            this.btnagregar_puesto.setEnabled(false);
            this.btnmodificar_puesto.setEnabled(true);
            this.btneliminar_puesto.setEnabled(true);
            this.cmbuesto_estado.setEnabled(true);
        }
    }
    private void LimpiarInputs()
    {
        this.txtpuesto_descripcion.setText(null);
  
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpuesto_descripcion = new javax.swing.JTextField();
        btnagregar_puesto = new javax.swing.JButton();
        btnmodificar_puesto = new javax.swing.JButton();
        btneliminar_puesto = new javax.swing.JButton();
        cmbuesto_estado = new javax.swing.JComboBox<>();
        lberrordescripcion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 47, 61));

        txtpuesto_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpuesto_descripcionActionPerformed(evt);
            }
        });

        btnagregar_puesto.setText("Agregar");
        btnagregar_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_puestoActionPerformed(evt);
            }
        });

        btnmodificar_puesto.setText("Modificar");
        btnmodificar_puesto.setEnabled(false);
        btnmodificar_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_puestoActionPerformed(evt);
            }
        });

        btneliminar_puesto.setText("Eliminar");
        btneliminar_puesto.setEnabled(false);
        btneliminar_puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_puestoActionPerformed(evt);
            }
        });

        cmbuesto_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACT", "INA" }));
        cmbuesto_estado.setEnabled(false);

        lberrordescripcion.setForeground(new java.awt.Color(255, 51, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fgodo\\OneDrive\\Documentos\\GitHub\\proyectotiendarepuestos\\pry_TiendaRepuestos\\src\\Imagenes\\Logomantenimiento.PNG")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 29)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(230, 230, 230));
        jLabel5.setText("Mantenimiento de Empleados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lberrordescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnagregar_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmodificar_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtpuesto_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbuesto_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpuesto_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbuesto_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lberrordescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificar_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_puestoActionPerformed
        if(!PuestoControlador.Mantenimientopuesto("editar", this.IdPue,
            this.txtpuesto_descripcion.getText(),this.cmbuesto_estado.getSelectedItem().toString(),lberrordescripcion))
        {           
            this.LimpiarInputs();
            PuestosPantalla puestopantalla = new PuestosPantalla();
            puestopantalla.setVisible(true); 
            dispose();
        }  
    }//GEN-LAST:event_btnmodificar_puestoActionPerformed

    private void btnagregar_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_puestoActionPerformed

        if(!PuestoControlador.Mantenimientopuesto("insertar", this.IdPue,
            this.txtpuesto_descripcion.getText(),"ACT",this.lberrordescripcion))
        {           
            this.LimpiarInputs();
            PuestosPantalla puestopantalla = new PuestosPantalla();
            puestopantalla.setVisible(true); 
            dispose();
        }  
    }//GEN-LAST:event_btnagregar_puestoActionPerformed

    private void txtpuesto_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpuesto_descripcionActionPerformed

    }//GEN-LAST:event_txtpuesto_descripcionActionPerformed

    private void btneliminar_puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_puestoActionPerformed
        if(PuestoControlador.Eliminarpuesto(this.IdPue))
        {
            this.LimpiarInputs();
            PuestosPantalla puestopantalla = new PuestosPantalla();
            puestopantalla.setVisible(true); 
            dispose();
        }        
    }//GEN-LAST:event_btneliminar_puestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_puestopantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_puestopantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_puestopantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_puestopantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento_puestopantalla().setVisible(true);
            }
        });
        try {
           // UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
           UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (ClassNotFoundException ex) { System.out.println("e");}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar_puesto;
    private javax.swing.JButton btneliminar_puesto;
    private javax.swing.JButton btnmodificar_puesto;
    private javax.swing.JComboBox<String> cmbuesto_estado;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lberrordescripcion;
    private javax.swing.JTextField txtpuesto_descripcion;
    // End of variables declaration//GEN-END:variables
}
