/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Conexiones.TempConexion;
import Controladores.PedidosControlador;
import Especiales.CrearPDF;
import Especiales.Validaciones;
import Modelos.CachePedidos;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author marce
 */
public class PedidosPantalla extends javax.swing.JFrame {

    /**
     * Creates new form PedidosPantalla
     */
    
    boolean bandeedit = false;
    
    public PedidosPantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
        CachePedidos cache = new CachePedidos();
        //Date fecha = new Date();
        //fecha_pedidos.setDate(fecha);
        PedidosControlador pedidocontrolador = new PedidosControlador();
        pedidocontrolador.setPlaceHolders(this.txtproveedor_pedidos, this.txtproducto_pedidos, this.txtproductodes_pedidos, this.txtprecio_pedidos);
        if(cache.isBandeProveedores()){
            PedidosControlador.agregarProveedor(txtproveedor_pedidos);
            btnbuscarproducto.setEnabled(true);
        }
        if(cache.isBandeProductos()){
            PedidosControlador.agregarProducto(txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            PedidosControlador.Llenartablapedidostemp(tabla_pedidos);
            spinnercanti_pedidos.setEnabled(true);
            btnagregarprod_pedidos.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_pedidos = new javax.swing.JTable();
        txtproveedor_pedidos = new javax.swing.JTextField();
        btnbuscarproveedor = new javax.swing.JButton();
        btnbuscarproducto = new javax.swing.JButton();
        txtproducto_pedidos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtproductodes_pedidos = new javax.swing.JTextArea();
        spinnercanti_pedidos = new javax.swing.JSpinner();
        txtempleado_pedidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnagregarprod_pedidos = new javax.swing.JButton();
        btnimprimir_pedidos = new javax.swing.JButton();
        btnregresar_pedidos = new javax.swing.JButton();
        txtprecio_pedidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipPago = new javax.swing.JComboBox<>();
        btncancelar_pedidos = new javax.swing.JButton();
        btneliminarprod_pedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 47, 61));

        tabla_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_pedidos.getTableHeader().setReorderingAllowed(false);
        tabla_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_pedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_pedidos);
        if (tabla_pedidos.getColumnModel().getColumnCount() > 0) {
            tabla_pedidos.getColumnModel().getColumn(0).setResizable(false);
            tabla_pedidos.getColumnModel().getColumn(1).setResizable(false);
            tabla_pedidos.getColumnModel().getColumn(2).setResizable(false);
            tabla_pedidos.getColumnModel().getColumn(3).setResizable(false);
        }

        txtproveedor_pedidos.setEditable(false);
        txtproveedor_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproveedor_pedidosActionPerformed(evt);
            }
        });

        btnbuscarproveedor.setBackground(new java.awt.Color(70, 104, 116));
        btnbuscarproveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarproveedor.setText("Buscar Proveedor");
        btnbuscarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproveedorActionPerformed(evt);
            }
        });

        btnbuscarproducto.setBackground(new java.awt.Color(70, 104, 116));
        btnbuscarproducto.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscarproducto.setText("Buscar Producto");
        btnbuscarproducto.setEnabled(false);
        btnbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarproductoActionPerformed(evt);
            }
        });

        txtproducto_pedidos.setEditable(false);
        txtproducto_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproducto_pedidosActionPerformed(evt);
            }
        });

        txtproductodes_pedidos.setEditable(false);
        txtproductodes_pedidos.setColumns(20);
        txtproductodes_pedidos.setRows(5);
        jScrollPane2.setViewportView(txtproductodes_pedidos);

        spinnercanti_pedidos.setEditor(new javax.swing.JSpinner.NumberEditor(spinnercanti_pedidos, ""));
        spinnercanti_pedidos.setEnabled(false);
        spinnercanti_pedidos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnercanti_pedidosStateChanged(evt);
            }
        });
        spinnercanti_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spinnercanti_pedidosMouseClicked(evt);
            }
        });

        txtempleado_pedidos.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad:");

        btnagregarprod_pedidos.setBackground(new java.awt.Color(70, 104, 116));
        btnagregarprod_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarprod_pedidos.setText("Guardar Producto");
        btnagregarprod_pedidos.setEnabled(false);
        btnagregarprod_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarprod_pedidosActionPerformed(evt);
            }
        });

        btnimprimir_pedidos.setBackground(new java.awt.Color(70, 104, 116));
        btnimprimir_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimir_pedidos.setText("Realizar Pedido");
        btnimprimir_pedidos.setActionCommand("");
        btnimprimir_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_pedidosActionPerformed(evt);
            }
        });

        btnregresar_pedidos.setBackground(new java.awt.Color(70, 104, 116));
        btnregresar_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnregresar_pedidos.setText("Regresar");
        btnregresar_pedidos.setActionCommand("");
        btnregresar_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar_pedidosActionPerformed(evt);
            }
        });

        txtprecio_pedidos.setEditable(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logomantenimiento.PNG"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Generar Orden de Compra");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbTipPago.setBackground(new java.awt.Color(70, 104, 116));
        cmbTipPago.setForeground(new java.awt.Color(255, 255, 255));
        cmbTipPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de pago...", "Crédito", "Al contado", "Transferencia" }));

        btncancelar_pedidos.setBackground(new java.awt.Color(70, 104, 116));
        btncancelar_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar_pedidos.setText("Cancelar Pedido");
        btncancelar_pedidos.setActionCommand("");
        btncancelar_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar_pedidosActionPerformed(evt);
            }
        });

        btneliminarprod_pedidos.setBackground(new java.awt.Color(70, 104, 116));
        btneliminarprod_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btneliminarprod_pedidos.setText("Eliminar Producto");
        btneliminarprod_pedidos.setEnabled(false);
        btneliminarprod_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarprod_pedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnregresar_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(btncancelar_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnimprimir_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtproducto_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnbuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtproveedor_pedidos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnbuscarproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnercanti_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtempleado_pedidos)
                                    .addComponent(txtprecio_pedidos)
                                    .addComponent(btnagregarprod_pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbTipPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btneliminarprod_pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(87, 87, 87)
                            .addComponent(jLabel4))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtproveedor_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipPago, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtempleado_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtprecio_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnercanti_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnagregarprod_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btneliminarprod_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnbuscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproducto_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnimprimir_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregresar_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresar_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar_pedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregresar_pedidosActionPerformed

    private void btnimprimir_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_pedidosActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String Date;
        Date fecha = new Date();
        Date = formatter.format(fecha);
        if(Validaciones.validarSelecciones(txtproveedor_pedidos, cmbTipPago, tabla_pedidos)){
            CachePedidos cache = new CachePedidos();
            PedidosControlador.seleccionPago(cmbTipPago);
            if(!PedidosControlador.Mantenimientopedidos("insertar", 0, cache.getProcodigo(),Date, 1, "ACT")){
                CrearPDF pdf = new CrearPDF( Date);
                pdf.crearPDF();
            }
            
            PedidosControlador.Mantenimientotemp("eliminar", txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            
        }
        
    }//GEN-LAST:event_btnimprimir_pedidosActionPerformed

    private void btnagregarprod_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarprod_pedidosActionPerformed
        if(bandeedit==true){
            PedidosControlador.Mantenimientotemp("editar", txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            PedidosControlador.Llenartablapedidostemp(tabla_pedidos);
            PedidosControlador.limpiarTextos(txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            btneliminarprod_pedidos.setEnabled(false);
        }else{
            PedidosControlador.Mantenimientotemp("insertar", txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            PedidosControlador.Llenartablapedidostemp(tabla_pedidos);
            PedidosControlador.limpiarTextos(txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            btnbuscarproveedor.setEnabled(false);
        }
        //PedidosControlador.agregarFilaProducto(tabla_pedidos, txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
    }//GEN-LAST:event_btnagregarprod_pedidosActionPerformed

    private void spinnercanti_pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinnercanti_pedidosMouseClicked
        /*
        }*/
        System.out.println(spinnercanti_pedidos.getValue().toString());
    }//GEN-LAST:event_spinnercanti_pedidosMouseClicked

    private void spinnercanti_pedidosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnercanti_pedidosStateChanged
        PedidosControlador.cambioSpinner(spinnercanti_pedidos);

    }//GEN-LAST:event_spinnercanti_pedidosStateChanged

    private void txtproducto_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproducto_pedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproducto_pedidosActionPerformed

    private void btnbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproductoActionPerformed
        ProductosPantalla pro = new ProductosPantalla();
        pro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbuscarproductoActionPerformed

    private void btnbuscarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarproveedorActionPerformed
        ProveedoresPantalla pro = new ProveedoresPantalla();
        pro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbuscarproveedorActionPerformed

    private void txtproveedor_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproveedor_pedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproveedor_pedidosActionPerformed

    private void btncancelar_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar_pedidosActionPerformed
        PedidosControlador.limpiarTodo(txtproveedor_pedidos, txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos, cmbTipPago, btnbuscarproveedor, btnbuscarproducto, btnagregarprod_pedidos);
        PedidosControlador.Llenartablapedidostemp(tabla_pedidos);
    }//GEN-LAST:event_btncancelar_pedidosActionPerformed

    private void tabla_pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_pedidosMouseClicked
        int seleccion = this.tabla_pedidos.rowAtPoint(evt.getPoint());
        txtproducto_pedidos.setText(String.valueOf(this.tabla_pedidos.getModel().getValueAt(seleccion, 0)));
        txtproductodes_pedidos.setText(String.valueOf(this.tabla_pedidos.getModel().getValueAt(seleccion, 1)));
        txtprecio_pedidos.setText(String.valueOf(this.tabla_pedidos.getModel().getValueAt(seleccion, 2)));
        spinnercanti_pedidos.setValue(this.tabla_pedidos.getModel().getValueAt(seleccion, 3));
        bandeedit=true;
        btneliminarprod_pedidos.setEnabled(true);
    }//GEN-LAST:event_tabla_pedidosMouseClicked

    private void btneliminarprod_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarprod_pedidosActionPerformed
            PedidosControlador.Mantenimientotemp("quitar", txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            PedidosControlador.Llenartablapedidostemp(tabla_pedidos);
            PedidosControlador.limpiarTextos(txtproducto_pedidos, txtproductodes_pedidos, txtprecio_pedidos, spinnercanti_pedidos);
            btneliminarprod_pedidos.setEnabled(false);
    }//GEN-LAST:event_btneliminarprod_pedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           // UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
           UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(ClientesPantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosPantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarprod_pedidos;
    private javax.swing.JButton btnbuscarproducto;
    private javax.swing.JButton btnbuscarproveedor;
    private javax.swing.JButton btncancelar_pedidos;
    private javax.swing.JButton btneliminarprod_pedidos;
    private javax.swing.JButton btnimprimir_pedidos;
    private javax.swing.JButton btnregresar_pedidos;
    private javax.swing.JComboBox<String> cmbTipPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinnercanti_pedidos;
    private javax.swing.JTable tabla_pedidos;
    private javax.swing.JTextField txtempleado_pedidos;
    private javax.swing.JTextField txtprecio_pedidos;
    private javax.swing.JTextField txtproducto_pedidos;
    private javax.swing.JTextArea txtproductodes_pedidos;
    private javax.swing.JTextField txtproveedor_pedidos;
    // End of variables declaration//GEN-END:variables
}
